[theme]
primaryColor = "#00e676"          # Verde neón para botones, líneas de selección y detalles
backgroundColor = "#0e1117"      # Fondo oscuro profundo
secondaryBackgroundColor = "#1f2937" # Gris oscuro para la Sidebar y tarjetas
textColor = "#ffffff"            # Texto blanco de alta legibilidad
font = "sans serif"