[theme]
primaryColor = "#4c566a"          # Gris oscuro nórdico para enfoque en selecciones
backgroundColor = "#f8f9fa"      # Blanco hueso (evita el deslumbramiento)
secondaryBackgroundColor = "#e5e9f0" # Gris azulado claro para la Sidebar y tarjetas
textColor = "#2e3440"            # Gris grafito oscuro para máxima legibilidad
font = "sans serif"